bookingApp/admins/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app, abort
from flask_login import login_user, current_user, logout_user, login_required
from bookingApp import db, bcrypt, Mail, SGmail
from bookingApp.admins.forms import *
from bookingApp.models import *
from werkzeug.utils import secure_filename
import os, csv

admins = Blueprint("admins", __name__, template_folder='templates', static_folder='static')

#####  Logout User  #####
@admins.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.splash'))


#####  Panel  ######
@admins.route("/panel")
@login_required
def panel():
    products = Products.query.all()
    orders = Orders.query.all()
    users = Users.query.all()
    vendors = Vendors.query.all()
    customers = Customers.query.all()
    return render_template("admins/index.html", title="Admin", products=products, orders=orders, totalTransactions=len(customers), vendors=vendors, userE=False)

#####  Panel - Edit User Modal  ######
@admins.route("/panel/Edit", methods=["GET","POST"])
@login_required
def panelEdit():
    form = EditUserForm()
    products = Products.query.all()
    orders = Orders.query.all()
    users = Users.query.all()
    vendors = Vendors.query.all()

    if form.validate_on_submit():
        current_user.forename = form.forename.data
        current_user.surname = form.surname.data
        current_user.email = str(form.email.data).lower()
        current_user.mobile = form.mobile.data

        if form.password.data != "":
            if bcrypt.check_password_hash(current_user.password, form.oldPassword.data):
                current_user.password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for('admins.panel'))

    elif request.method == "GET":
        form.forename.data = current_user.forename
        form.surname.data = current_user.surname
        form.email.data = current_user.email
        form.mobile.data = current_user.mobile

    return render_template("admins/index.html", title="Admin", products=products, orders=orders, totalTransactions=len(users), vendors=vendors, userE=True, form=form)


####  attendee List - View  ####
@admins.route("/attendeeList")
@login_required
def attendeeList():
    attendees = Customers.query.all()
    orders = Orders.query.all()
    products = Products.query.all()
    return render_template("admins/attendeeList.html", title="attendee List", attendees=attendees, orders=orders, products=products, customerD=None)

####  attendee List - Delete Modal  ####
@admins.route("/attendeeList/<int:customerID>")
@login_required
def attendeeListDelete(customerID):
    customerD = Customers.query.get_or_404(customerID)
    attendees = Customers.query.all()
    orders = Orders.query.all()
    products = Products.query.all()
    return render_template("admins/attendeeList.html", title="attendee List", attendees=attendees, orders=orders, products=products, customerD=customerD)

####  Delete Customer  ####
@admins.route("/DC/<int:customerID>")
@login_required
def deleteCustomer(customerID):
    if current_user.admin != 1:
        abort(403)
    customerD = Customers.query.get_or_404(customerID)
    orders = Orders.query.all()

    for order in orders:
        if order.referenceNumber == customerD.id:
            db.session.delete(order)

    db.session.delete(customerD)
    db.session.commit()
    flash(f"Customer: {customerD.forename} {customerD.surname} and Associated Orders Deleted", "success")
    return redirect(url_for("admins.attendeeList"))


####  Vendor List  ####
@admins.route("/vendorList")
@login_required
def vendorList():
    vendors = Vendors.query.all()
    return render_template("admins/vendorList.html", title="Vendor List", vendors=vendors, vendorD=None)


####  Edit Vendor  ####
@admins.route("/vendorList/edit/<int:vendorID>", methods=["GET", "POST"])
@login_required
def editVendor(vendorID):
    vendors = Vendors.query.all()
    form = EditVendorForm()
    for vendor in vendors:
        if vendor.id == vendorID:
            if form.validate_on_submit():
                vendor.name = form.companyName.data
                vendor.email = str(form.companyEmail.data).lower()
                vendor.mobile = form.companyMobile.data

                db.session.commit()
                flash("Vendor details have been updated!", "success")
                return redirect(url_for('admins.vendorList'))

            elif request.method == "GET":
                form.companyName.data = vendor.name
                form.companyEmail.data = vendor.email
                form.companyMobile.data = vendor.mobile
    
    return render_template("admins/vendorList.html", title="Vendor List", vendors=vendors, vendorD=None, editVendor=True, form=form)


####  Email Individual Vendor  ####
@admins.route("/vendorList/email/<int:vendorID>")
@login_required
def emailVendor(vendorID):
    vendors = Vendors.query.all()
    orders = Orders.query.all()
    products = Products.query.all()
    for vendor in vendors:
        if vendor.id == vendorID:
            if vendor.email != None:
                message = Mail(
                    from_email="noreply@atcjbtrrsvp.com",
                    to_emails=vendor.email,
                )
                message.template_id = "d-a51ebb7b223d40bd92ff66781767ff3e"
                
                with open('bookingApp/admins/templates/admins/emails/vendorUpdate.html', 'r') as f:
                    content = f.read()

                total = 0
                contentStr = ""
                orderedProducts = {}
                for product in products:
                    if product.vendorID == vendor.id:
                        for order in orders:
                            if order.productID == product.id:
                                if product.id in orderedProducts:
                                    orderedProducts[product.id] += order.quantity
                                else:
                                    orderedProducts[product.id] = order.quantity
                                total += order.quantity
                
                        contentStr += f"""
                        <tr>
                            <td>{product.name.replace("_", " ")}</td>
                            <td>{orderedProducts.get(product.id)}</td>
                        </tr>
                        """

                message.dynamic_template_data = {
                    'vendorName': vendor.name,
                    'content': content.format(tbody=contentStr, total=total),
                }
                SGmail.send(message)
                flash(f"Report has been emailed to vendor {vendor.name}.", "success")
                return redirect(url_for('admins.vendorList'))
            else:
                flash(f"Sorry, vendor {vendor.name} does not have an associated email, please add this and try again.", "warning")
                return redirect(url_for('admins.vendorList'))


####  Email All Vendors  ####
@admins.route("/vendorList/emailAll")
@login_required
def emailAllVendors():
    vendors = Vendors.query.all()
    orders = Orders.query.all()
    products = Products.query.all()
    for vendor in vendors:
        if vendor.email != None:
            message = Mail(
                from_email="noreply@atcjbtrrsvp.com",
                to_emails=vendor.email,
            )
            message.template_id = "d-a51ebb7b223d40bd92ff66781767ff3e"
            
            with open('bookingApp/admins/templates/admins/emails/vendorUpdate.html', 'r') as f:
                content = f.read()

            total = 0
            contentStr = ""
            orderedProducts = {}
            for product in products:
                if product.vendorID == vendor.id:
                    for order in orders:
                        if order.productID == product.id:
                            if product.id in orderedProducts:
                                orderedProducts[product.id] += order.quantity
                            else:
                                orderedProducts[product.id] = order.quantity
                            total += order.quantity
            
                    contentStr += f"""
                    <tr>
                        <td>{product.name.replace("_", " ")}</td>
                        <td>{orderedProducts.get(product.id)}</td>
                    </tr>
                    """

            message.dynamic_template_data = {
                'vendorName': vendor.name,
                'content': content.format(tbody=contentStr, total=total),
            }
            SGmail.send(message)
            flash(f"Report has been emailed to vendor {vendor.name}.", "success")
        else:
            flash(f"Sorry, vendor {vendor.name} does not have an associated email, please add this and try again.", "warning")
    return redirect(url_for('admins.vendorList'))


#####  Vendor List - Delete Modal  #####
@admins.route("/vendorList/<int:vendorID>")
@login_required
def vendorListDelete(vendorID):
    vendors = Vendors.query.all()
    vendorD = Vendors.query.get_or_404(vendorID)
    return render_template("admins/vendorList.html", title="Vendor List", vendors=vendors, vendorD=vendorD)


####  Delete Vendor  ####
@admins.route("/vendorList/DV/<int:vendorID>")
@login_required
def deleteVendor(vendorID):
    if current_user.admin != 1:
        abort(403)
    vendorD = Vendors.query.get_or_404(vendorID)
    orders = Orders.query.all()
    products = Products.query.all()
    users = Users.query.all()
    
    for order in orders:
        for product in products:
            if product.vendorID == vendorD.id:
                if order.productID == product.id:
                    db.session.delete(order)
    
    for product in products:
        if product.vendorID == vendorD.id:

bookingApp/admins/templates/admins/addProduct.html
{% extends 'admins/layout.html' %}
{% from '_helpers.html' import formInput %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="col-lg-10">
                <div class="overview-item overview-item--c2">
                    <div class="overview__inner">
                        <div class="overview-box clearfix">
                            <h2 style="color: black;" class="title-1 m-b-25">Add Product</h2>
                            <form method="POST" action="">
                                {{ form.hidden_tag() }}
                                <div class="row">
                                    <!-- Text Inputs -->
                                    {{ formInput(form.name, placeholder="Enter Product Name", grid="col-md-6") }}

                                    {{ formInput(form.price, grid="col-md-6", type="number", step="0.01", min=0, value=0) }}

                                    {{ formInput(form.description, placeholder="Enter Description", grid="col-md-9") }}

                                    <div class="form-group col-md-6">
                                        {{ form.selectVendor.label() }}
                                        {{ form.selectVendor(class="form-control") }}
                                    </div>

                                    <div class="form-group col-md-6">
                                        {{ form.category.label }}
                                        <div class="form-check" id="category">
                                            <div class="radio">
                                                <label for="category-0" class="form-check-label ">
                                                    <input type="radio" id="category-0" name="category" value="t_"
                                                        checked class="form-check-input">Ticket
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label for="category-1" class="form-check-label ">
                                                    <input type="radio" id="category-1" name="category" value=""
                                                        class="form-check-input">Catering
                                                </label>
                                            </div>
                                        </div>
                                    </div>


                                    <!-- Button -->
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form.submit(class="au-btn au-btn--green m-b-20") }}
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bookingApp/admins/templates/admins/attendeeList.html
{% extends 'admins/layout.html' %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="title-1 m-b-25">Attendees</h2>
                    <input type="text" name="search" id="search" class="form-control au-input au-input--full m-b-25"
                        placeholder="Search:">
                    <script>
                        $(document).ready(function () {
                            $("#search").on("keyup", function () {
                                var value = $(this).val().toLowerCase();
                                $("#attendeeTable tbody tr").filter(function () {
                                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                                });
                            });
                        });
                    </script>
                    <div class="table-responsive table--no-card m-b-40">
                        <table class="table table-borderless table-striped table-earning" id="attendeeTable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Tickets RSVP'd</th>
                                    <th>Catering RSVP'd</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for attendee in attendees %}

                                {% set rsvps = namespace(tickets=0, catering=0) %}
                                {% for order in orders %}
                                {% if order.referenceNumber == attendee.id %}
                                {% for product in products %}
                                {% if order.productID == product.id %}
                                {% if product.name[:2] == "t_" %}
                                {% set rsvps.tickets = rsvps.tickets + 1 %}
                                {% else %}
                                {% set rsvps.catering = rsvps.catering + 1 %}
                                {% endif %}
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                                <tr>
                                    <td>{{ attendee.forename }} {{ attendee.surname }}</td>
                                    <td>{{ attendee.email }}</td>
                                    <td>{{ rsvps.tickets }}</td>
                                    <td>{{ rsvps.catering }}</td>
                                    <td>
                                        <a href="{{ url_for('admins.attendeeListDelete', customerID=attendee.id) }}"
                                            class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Delete RSVP Modal -->
    {% if customerD != None %}
    <div class="modal fade" id="deleteRSVPModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Remove RSVP</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- body -->
                <div class="modal-body">
                    <b>Warning!</b><br>
                    This will remove the customer and all associated orders from the database <u>permanently</u>!
                    <br><br>
                    Deleting record: {{ customerD.forename }} {{ customerD.surname }}
                </div>

                <!-- footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
                    <a href="{{ url_for('admins.deleteCustomer', customerID=customerD.id) }}"
                        class="btn btn-danger">DELETE RECORD</a>
                </div>
            </div>
        </div>
    </div>

    <script>$("#deleteRSVPModal").modal();</script>
    {% endif %}

</div>
{% endblock content %}

bookingApp/admins/templates/admins/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard</title>

    <!-- Jquery JS-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

    <!-- Fontfaces CSS-->
    <link href="{{ url_for('admins.static', filename='css/font-face.css" rel="stylesheet') }}" media="all">
    <link href="{{ url_for('admins.static', filename='vendor/font-awesome-4.7/css/font-awesome.min.css') }}"
        rel="stylesheet" media="all">
    <link href="{{ url_for('admins.static', filename='vendor/font-awesome-5/css/fontawesome-all.min.css') }}"
        rel="stylesheet" media="all">
    <link href="{{ url_for('admins.static', filename='vendor/mdi-font/css/material-design-iconic-font.min.css') }}"
        rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{{ url_for('admins.static', filename='vendor/bootstrap-4.1/bootstrap.min.css') }}" rel="stylesheet"
        media="all">

    <!-- Vendor CSS-->
    <link
        href="{{ url_for('admins.static', filename='vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css') }}"
        rel="stylesheet" media="all">
    <link href="{{ url_for('admins.static', filename='vendor/slick/slick.css') }}" rel="stylesheet" media="all">
    <link href="{{ url_for('admins.static', filename='vendor/perfect-scrollbar/perfect-scrollbar.css') }}"
        rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{ url_for('admins.static', filename='css/theme.css') }}" rel="stylesheet" media="all">

</head>

<body>
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="#">
                            <h4>
                                <i class="fas fa-user-circle">
                                    {{ current_user.forename }} {{ current_user.surname }}
                                </i>
                            </h4>
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li>
                            <a href="{{ url_for('admins.panel') }}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.attendeeList') }}">Attendee List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.vendorList') }}">Vendor List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.productList') }}">Product List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.students') }}">Students</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="{{ url_for('admins.panelEdit') }}">
                    <h4>
                        <i class="fas fa-user-circle">
                            {{ current_user.forename }} {{ current_user.surname }}
                        </i>
                    </h4>
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li>
                            <a href="{{ url_for('admins.panel') }}">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.attendeeList') }}">Attendee List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.vendorList') }}">Vendor List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.productList') }}">Product List</a>
                        </li>
                        <li>
                            <a href="{{ url_for('admins.students') }}">Students</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <div class="section__content section__content--p30">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages  %}
                <div class="alert alert-{{ category }}" style="margin-top: 15px;">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
            {% block content %}{% endblock content %}
        </div>

    </div>

    <!-- Vendor JS       -->
    <script src="{{ url_for('admins.static', filename='vendor/slick/slick.min.js') }}">
    </script>
    <script src="{{ url_for('admins.static', filename='vendor/bootstrap-progressbar/bootstrap-progressbar.min.js') }}">
    </script>
    <script src="{{ url_for('admins.static', filename='vendor/counter-up/jquery.waypoints.min.js') }}"></script>
    <script src="{{ url_for('admins.static', filename='vendor/counter-up/jquery.counterup.min.js') }}">
    </script>
    <script src="{{ url_for('admins.static', filename='vendor/circle-progress/circle-progress.min.js') }}"></script>
    <script src="{{ url_for('admins.static', filename='vendor/perfect-scrollbar/perfect-scrollbar.js') }}"></script>
    <script src="{{ url_for('admins.static', filename='vendor/chartjs/Chart.bundle.min.js') }}"></script>

    <!-- Main JS-->
    <script src="{{ url_for('admins.static', filename='js/main.js') }}"></script>

</body>

</html>
<!-- end document-->

bookingApp/admins/templates/admins/vendorList.html
{% extends 'admins/layout.html' %}
{% from '_helpers.html' import formInput %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="overview-wrap">
                        <h2 class="title-1 m-b-25">Vendors</h2>
                        <div class="table-data__tool-right">
                            <a href="{{ url_for('admins.emailAllVendors') }}" class="au-btn btn-info m-b-25">Email All
                                Vendors</a>
                            <a href="{{ url_for('admins.registerVendor') }}" class="au-btn btn-success m-b-25">Add
                                Vendor</a>
                        </div>
                    </div>
                    <input type="text" name="search" id="search" class="form-control au-input au-input--full m-b-25"
                        placeholder="Search:">
                    <script>
                        $(document).ready(function () {
                            $("#search").on("keyup", function () {
                                var value = $(this).val().toLowerCase();
                                $("#vendorTable tbody tr").filter(function () {
                                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                                });
                            });
                        });
                    </script>
                    <div class="table-responsive table--no-card m-b-40">
                        <table class="table table-borderless table-striped table-earning" id="vendorTable">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Contact Number</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for vendor in vendors %}
                                <tr>
                                    <td>{{ vendor.name }}</td>
                                    <td>{{ vendor.email }}</td>
                                    <td>{{ vendor.mobile }}</td>
                                    <td><a href="{{ url_for('admins.emailVendor', vendorID=vendor.id) }}"
                                            class="btn btn-info">Email Report</a></td>
                                    <td><a href="{{ url_for('admins.editVendor', vendorID=vendor.id) }}"
                                            class="btn btn-outline-primary">Edit Vendor</a></td>
                                    <td>
                                        <a href="{{ url_for('admins.vendorListDelete', vendorID=vendor.id) }}"
                                            class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete RSVP Modal -->
    {% if vendorD != None %}
    <div class="modal fade" id="deleteVendorModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Remove Vendor</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- body -->
                <div class="modal-body">
                    <b>Warning!</b><br>
                    This will remove the vendor and all associated products from the database <u>permanently</u>!
                    This includes any products already ordered (they will be removed from attendees orders).
                    <br><br>
                    Deleting record: {{ vendorD.name }}
                </div>

                <!-- footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
                    <a href="{{ url_for('admins.deleteVendor', vendorID=vendorD.id) }}" class="btn btn-danger">DELETE
                        RECORD</a>
                </div>
            </div>
        </div>
    </div>
    <script>$("#deleteVendorModal").modal();</script>
    {% endif %}

    <!-- Edit Vendor Modal -->
    {% if editVendor == True %}
    <div class="modal fade" id="editVendor">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edit Vendor Details</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <form method="POST" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <!-- body -->
                    <div class="modal-body">
                        <div class="row">
                            <!-- Text Inputs -->
                            {{ formInput(form.companyName, placeholder="Enter Company Name", grid="col-md-6") }}

                            {{ formInput(form.companyEmail, placeholder="Enter Company Email", grid="col-md-6") }}

                            {{ formInput(form.companyMobile, placeholder="Enter Company Mobile", grid="col-md-6") }}
                        </div>
                    </div>

                    <!-- footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                        {{ form.submit(class="btn btn-success") }}
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>$("#editVendor").modal();</script>
    {% endif %}
</div>
{% endblock content %}